version: '3.7'

services:

  mongoexpress-ssh:
    build: .
    image: flaviostutz/mongoexpress-ssh
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - SSH_ROOT_PASSWORD=admin123
    ports: 
      - 8081:8081
      - "2222:2222"

  mongo:
    image: mongo:4.4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    deploy:
      replicas: 1
    ports:
      - 27017:27017

